name: PHP Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Cambia según tu versión PHP

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit # Cambia según tu comando de prueba

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Cambia según tu versión PHP
          registry-url: https://PACKAGIST_URL

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Publish Package
        run: composer publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
